# Generated by Django 6.0.3 on 2026-03-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', '-created_date'], name='idx_task_status_created_date'),
        ),
    ]
